### PR TITLE
Tracmobility/halil-sallabas-senior-frontend-task

### PR DESCRIPTION
**Pull request by hsallabas**
Completed Tracmobility senior frontend task

### CODE REVIEW

**Comment by wangzilong** [comment]
Hey @hsallabas 
Could you please commit your package.json? and describe how to run it locally in README.MD file?

**Comment by hsallabas** [comment]
I sent them. I started to develop my private repo so I needed to merge two different git file :) I didn't want to lose my commits.

**Comment by hsallabas** [comment]
Did you run the project? Is there any problem? If you have any trouble running the project, please try the code in this repo. https://github.com/hsallabas/trac-mobility

**Comment by hsallabas** [comment]
wrong pull request

**Pull request closed without merging**
